a: https://beta.catalystapp.co/Artist$1
ar: https://beta.catalystapp.co/Artist$1
art: https://beta.catalystapp.co/Artist$1
artist: https://beta.catalystapp.co/Artist$1
artists: https://beta.catalystapp.co/Artist$1

cr: https://beta.catalystapp.co/Artist$1
cre: https://beta.catalystapp.co/Artist$1
create: https://beta.catalystapp.co/Artist$1
creator: https://beta.catalystapp.co/Artist$1
creators: https://beta.catalystapp.co/Artist$1

c: https://beta.catalystapp.co/Character/View$1
ch: https://beta.catalystapp.co/Character/View$1
char: https://beta.catalystapp.co/Character/View$1
character: https://beta.catalystapp.co/Character/View$1
characters: https://beta.catalystapp.co/Character/View$1

co: https://beta.catalystapp.co/Commission$1
comm: https://beta.catalystapp.co/Commission$1
commission: https://beta.catalystapp.co/Commission$1

u: https://beta.catalystapp.co/User$1
us: https://beta.catalystapp.co/User$1
user: https://beta.catalystapp.co/User$1

d: https://discord.gg/EECUcnT
dis: https://discord.gg/EECUcnT
discord: https://discord.gg/EECUcnT

t: https://telegram.dog/catalystapp
te: https://telegram.dog/catalystapp
tele: https://telegram.dog/catalystapp
telegram: https://telegram.dog/catalystapp
telegram-announcements: https://telegram.dog/catalystapp_announcements

gh: https://github.com/catalyst-app/Catalyst
git: https://github.com/catalyst-app/Catalyst
github: https://github.com/catalyst-app/Catalyst

fa: https://furaffinity.net/user/catalystapp/

fn: https://beta.furrynetwork.com/catalyst/

ig: https://instagram.com/catalyst.app/
insta: https://instagram.com/catalyst.app/

trello: https://trello.com/b/X37KEv4A/catalyst

tw: https://twitter.com/catalystapp_co
twit: https://twitter.com/catalystapp_co
twitter: https://twitter.com/catalystapp_co

steam: https://steamcommunity.com/groups/catalystapp

da: https://catalystapp.deviantart.com/
deviantart: https://catalystapp.deviantart.com/

weasyl: https://weasyl.com/~catalystapp/

redd: https://reddit.com/r/catalystapp/
reddit: https://reddit.com/r/catalystapp/

tos: https://catalystapp.co/Help/ToS

pp: https://catalystapp.co/Help/Privacy

kofi: https://ko-fi.com/catalystapp
ko-fi: https://ko-fi.com/catalystapp

tumblr: https://catalystapp-co.tumblr.com

fb: https://facebook.com/catalystapp.co
facebook: https://facebook.com/catalystapp.co

stream: https://www.twitch.tv/catalystapp

yt: https://www.youtube.com/channel/UCI8shN2z06O5cBJIfR2DIaA/live

k: https://kalka.io/

r: https://catalystapp.co/Character/View/8iu62tu/
riley: https://catalystapp.co/Character/View/8iu62tu/
riggle: https://catalystapp.co/Character/View/8iu62tu/

keer: https://catalystapp.co/Character/View/keeri/
keeri: https://catalystapp.co/Character/View/keeri/

p: https://patreon.com/catalyst
patreon:
  $root: https://patreon.com/catalyst
  keeri: https://beta.catalystapp.co/Character/View/w5nms1u/
  sinnerscout: https://beta.catalystapp.co/Artist/sinnerscout/
  mango: https://beta.catalystapp.co/Artist/Manguwu
  manguwu: https://beta.catalystapp.co/Artist/Manguwu
  toish: https://beta.catalystapp.co/Character/View/toish

staff:
  $root: https://catalystapp.co/#our-staff
  faux: https://beta.catalystapp.co/Character/View/fauxil/
  fauxil: https://beta.catalystapp.co/Character/View/fauxil/
  f: https://beta.catalystapp.co/Character/View/fauxil/
  l: https://beta.catalystapp.co/Character/View/lykai/
  lykai: https://beta.catalystapp.co/Character/View/lykai/
  foxxo: https://beta.catalystapp.co/Character/View/foxxo/
  ace: https://beta.catalystapp.co/Artist/acey/
  acey: https://beta.catalystapp.co/Artist/acey/
  egg: https://beta.catalystapp.co/Artist/acey/
  oneggiri: https://beta.catalystapp.co/Artist/acey/
