c: https://catalystapp.co/Character/View$1
ch: https://catalystapp.co/Character/View$1
char: https://catalystapp.co/Character/View$1
character: https://catalystapp.co/Character/View$1
characters: https://catalystapp.co/Character/View$1

u: https://catalystapp.co/User$1
us: https://catalystapp.co/User$1
user: https://catalystapp.co/User$1

gh: https://github.com/catalyst-app/Catalyst
git: https://github.com/catalyst-app/Catalyst
github: https://github.com/catalyst-app/Catalyst

tos: https://catalystapp.co/Help/ToS

pp: https://catalystapp.co/Help/Privacy

k: https://kalka.io/
kalka: https://kalka.io/

f: https://catalystapp.co/Character/View/fauxil/
faux: https://catalystapp.co/Character/View/fauxil/
fauxil: https://catalystapp.co/Character/View/fauxil/

r: https://catalystapp.co/Character/View/8iu62tu/
riley: https://catalystapp.co/Character/View/8iu62tu/
riggle: https://catalystapp.co/Character/View/8iu62tu/

keer: https://catalystapp.co/Character/View/keeri/
keeri: https://catalystapp.co/Character/View/keeri/

patreon:
  $root: https://catalystapp.co/
  keeri: https://catalystapp.co/Character/View/w5nms1u/
  toish: https://catalystapp.co/Character/View/toish

staff:
  $root: https://catalystapp.co/
  f: https://catalystapp.co/Character/View/fauxil/
  faux: https://catalystapp.co/Character/View/fauxil/
  fauxil: https://catalystapp.co/Character/View/fauxil/
  l: https://catalystapp.co/Character/View/lykai/
  lykai: https://catalystapp.co/Character/View/lykai/
  foxxo: https://catalystapp.co/Character/View/foxxo/
